################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

################################################################
# Dashboard
################################################################
api:
  dashboard: true

################################################################
# EntryPoints configuration
################################################################
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

http:
  middlewares:
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://askeynet.nl:9091/"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Email"
          - "Remote-Name"

################################################################
# LetsEncrypt configuration
################################################################
certificatesResolvers:
  letsencrypt:
    acme:
      email: peter_g_askey@live.co.uk
      storage: "letsencrypt/acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: http
#      dnsChallenge:
#        provider: mijnhost
#        delayBeforeCheck: 0

################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    network: proxy
