services:
  homepage:
    image: ghcr.io/alduthir/homepage:latest
    container_name: homepage
    networks:
      - proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`www.${HOST}`) || Host(`${HOST}`)"
      - "traefik.http.routers.homepage.service=homepage"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.tls.certresolver=letsencrypt"
      - "traefik.http.services.homepage.loadbalancer.server.port=80"
networks:
  proxy:
    name: proxy
    external: true
